<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

use Application\ViewHelper\DateFormat;

$this->headTitle('Пътни листи');
$this->headLink()->appendStylesheet($this->basePath('style/transire.css'));
?><div class="page">
    <div class="list-panel">
        <form action="" method="get">
            <div class="list-filters">
                <div class="list-filter-col">
                    <label>Дата: <input type="date" name="from_date" value="<?=$this->filters['from_date']?>"></label><br>
                    <label>до: <input type="date" name="to_date" value="<?=$this->filters['to_date']?>"></label>
                </div>
                <div class="list-filter-col">
                    <label>Шофьор: <select name="driver_id">
                            <?php foreach ($this->driverList as $d) { ?>
                                <option value="<?=$d->id?>"<?= $this->filters['driver_id'] == $d->id ? ' selected' : ''?>><?=$d->name?></option>
                            <?php } ?>
                        </select></label><br>
                    <label>Автомобил: <select name="vehicle_id">
                            <option value=""></option>
                            <?php foreach ($this->vehicleList as $v) { ?>
                                <option value="<?=$v->id?>"<?= $this->filters['vehicle_id'] == $v->id ? ' selected' : ''?>>[<?=$v->reg_nomer?>] <?=$v->model?></option>
                            <?php } ?>
                        </select></label>
                </div>
                <div class="list-filter-col">
                    <button type="submit" class="icon-button">search</button>
                </div>
            </div>
        </form>
        <?php if (!empty($this->models)) {?>
            <ul class="app-list transire-list">
                <?php foreach ($this->models as $m) { ?>
                    <li class="app-list-item">
                        <span class="app-list-item__graphic"><span class="material-symbols-sharp">receipt_long</span></span>
                        <span class="app-list-item__body">
                            <span class="app-list-item__body--line1"><?=$this->DateFormat()->fromString($m->date, DateFormat::FORMAT_ISO_DATETIME)?> <strong>[<?=$m->vehicle->reg_nomer?>]</strong></span>
                            <span class="app-list-item__body--line2"><?=$m->driver->name?></span>
                        </span>
                        <span class="app-list-item__controls">
                            <a href="<?=$this->url('application', ['controller'=>'transire','action'=>'edit'],['query'=>['id'=>$m->id]])?>"
                               class="icon-button">edit</a>
                            <a href="<?=$this->url('application', ['controller'=>'transire','action'=>'delete'],['query'=>['id'=>$m->id]])?>"
                               class="icon-button button-require-confirmation"
                            data-confirmation-message="Сигурни ли сте, че искате да изтриете този пътен лист? (Операцията е необратима!)">delete</a>
                        </span>
                    </li>
                <?php } ?>
            </ul>
            <?php
                $firstPage = $this->pagination->firstPageToList();
                $lastPage = $this->pagination->lastPageToList();
            ?>
            <?php if ($lastPage > $firstPage) { ?>
                <div class="pagination">
                    <?php if ($firstPage > 1) { ?>
                        <a class="pagination-button material-symbols-sharp" href="<?=$this->url('application', ['controller'=>'transire', 'action'=>'list'],['query'=>['page'=>1]])?>">first_page</a>
                    <?php } ?>
                    <?php for ($p = $firstPage; $p <= $lastPage && $p < $firstPage + 100; $p++) {?>
                        <a class="pagination-button" href="<?=$this->url('application', ['controller'=>'transire', 'action'=>'list'],['query'=>['page'=>$p]])?>"><?=$p?></a>
                    <?php } ?>
                    <?php if ($lastPage < $this->pagination->getTotalPages()) { ?>
                        <a class="pagination-button material-symbols-sharp" href="<?=$this->url('application', ['controller'=>'transire', 'action'=>'list'],['query'=>['page'=>$this->pagination->getTotalPages()]])?>">last_page</a>
                    <?php } ?>
                </div>
            <?php } ?>
        <?php } else { ?>
            <div class="content-stub">
                Няма въведени пътни листи!
            </div>
        <?php } ?>
    </div>
</div>
<a class="fab" href="<?=$this->url('application', ['controller'=>'transire', 'action'=>'add'])?>">add</a>
