<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
$this->headTitle($this->title);
$this->headLink()->appendStylesheet($this->basePath('style/vehicle.css'));
$this->headScript()->appendFile($this->basePath('script/vehicle.js'));
?><div class="page">
    <div class="form-panel">
        <form action="" method="post">
            <input type="hidden" name="id" value="<?=$this->model->id??''?>">
            <div class="form-fields">
                <div class="form-field-wrapper"><label for="inp-name">Име</label>
                    <input type="text" name="name" id="inp-name" value="<?=$this->model->name??''?>"></div>
                <div class="form-field-wrapper"><label for="inp-city">Град</label>
                    <input type="text" name="city" id="inp-city" value="<?=$this->model->city??''?>"></div>
            </div>

            <div class="form-controls">
                <a class="button" href="<?=$this->backlink?>"><span class="material-symbols-sharp">arrow_back</span> Назад</a>
                <button><span class="material-symbols-sharp">save</span> Запис</button>
            </div>
        </form>
    </div>
</div>
