<div class="head-panel">
    <span class="head-label"><?=$this->vehicle->reg_nomer?></span>
    <ul class="horizontal-menu">
        <li<?=$this->action === 'fueling' ? ' class="--selected"' : ''?>><a href="<?=$this->url('application', ['controller'=>'vehicle','action'=>'fueling'],['query'=>['vehicleId'=>$this->vehicle->id]])?>" class="icon-button">local_gas_station</a></li>
        <li<?=$this->action === 'maintenanceSchedule' ? ' class="--selected"' : ''?>><a href="<?=$this->url('application', ['controller'=>'vehicle','action'=>'maintenanceSchedule'],['query'=>['vehicleId'=>$this->vehicle->id]])?>" class="icon-button">calendar_month</a></li>
        <li<?=$this->action === 'repair' ? ' class="--selected"' : ''?>><a href="<?=$this->url('application', ['controller'=>'vehicle','action'=>'repair'],['query'=>['vehicleId'=>$this->vehicle->id]])?>" class="icon-button">build</a></li>
        <li<?=$this->action === 'edit' ? ' class="--selected"' : ''?>><a href="<?=$this->url('application', ['controller'=>'vehicle','action'=>'edit'],['query'=>['id'=>$this->vehicle->id]])?>" class="icon-button">edit</a></li>
    </ul>
</div>
