<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
$this->headTitle($this->title);
$this->headLink()->appendStylesheet($this->basePath('style/vehicle.css'));
$this->headScript()->appendFile($this->basePath('script/vehicle.js'));
?><div class="page">
    <div class="form-panel">
        <div class="info-header">
            <h3><?=$this->vehicle->reg_nomer?></h3>
            <span><?=$this->vehicle->model?></span>
            <span><?=$this->vehicle->color?></span>
            <span>(<?=$this->vehicle->year_manufactured?>)</span>
        </div>
        <form action="" method="post">
            <input type="hidden" name="id" value="<?=$this->model->id??''?>">
            <input type="hidden" name="vehicle_id" value="<?=$this->vehicle->id??''?>">
            <div class="form-fields">
                <div class="form-field-wrapper"><label for="inp-fuel_id">Вид гориво</label>
                    <select id="inp-fuel_id" name="fuel_id">
                        <?php foreach($this->fuels??[] as $f) {?>
                            <option value="<?=$f->id?>"><?=$f->name?></option>
                        <?php } ?>
                    </select></div>
                <div class="form-field-wrapper"><label for="inp-date_refueling">Дата на зареждане</label>
                    <input type="date" name="date_refueling" id="inp-date_refueling" value="<?=date('Y-m-d', strtotime($this->model->date_refueling??'now'))?>"></div>
                <div class="form-field-wrapper"><label for="inp-odometer">Одометър</label>
                    <input type="text" name="odometer" id="inp-odometer" value="<?=$this->model->odometer??''?>"></div>
                <div class="form-field-wrapper"><label for="inp-cost">Цена</label>
                    <input type="number" name="cost" id="inp-cost" step="0.01" value="<?=$this->model->cost??''?>"></div>
                <div class="form-field-wrapper"><label for="inp-quantity">Количество</label>
                    <input type="number" name="quantity" id="inp-quantity" step="0.01" value="<?=$this->model->quantity??''?>"></div>
            </div>

            <div class="form-controls">
                <a class="button" href="<?=$this->backlink?>"><span class="material-symbols-sharp">arrow_back</span> Назад</a>
                <button><span class="material-symbols-sharp">save</span> Запис</button>
            </div>
        </form>
    </div>
</div>
