<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
$this->headTitle($this->title);
$this->headTitle('Авто парк');
$this->headLink()->appendStylesheet($this->basePath('style/vehicle.css'));
?><div class="page">
    <div class="head-panel">
        <span class="head-label"><?=$this->vehicle->reg_nomer?></span>
        <ul class="horizontal-menu">
            <li<?=$this->action === 'fueling' ? ' class="--selected"' : ''?>><a href="<?=$this->url('application', ['controller'=>'vehicle','action'=>'fueling'],['query'=>['id'=>$this->vehicle->id]])?>" class="icon-button">local_gas_station</a></li>
            <li><a href="<?=$this->url('application', ['controller'=>'vehicle','action'=>'maintenance'],['query'=>['id'=>$this->vehicle->id]])?>" class="icon-button">calendar_month</a></li>
            <li><a href="<?=$this->url('application', ['controller'=>'vehicle','action'=>'repair'],['query'=>['id'=>$this->vehicle->id]])?>" class="icon-button">build</a></li>
            <li><a href="<?=$this->url('application', ['controller'=>'vehicle','action'=>'edit'],['query'=>['id'=>$this->vehicle->id]])?>" class="icon-button">edit</a></li>
        </ul>
    </div>
    <div class="list-panel">
        <?php if (!empty($this->models)) {?>
            <ul class="app-list fueling-list">
                <?php foreach ($this->models as $m) { ?>
                    <li class="app-list-item">
                        <span class="app-list-item__graphic"><span class="material-symbols-sharp">local_gas_station</span></span>
                        <span class="app-list-item__body">
                            <span class="app-list-item__body--line1"><?=$this->DateFormat()->fromString($m->date_refueling, 'Y-m-d H:i:s')?></span>
                            <span class="app-list-item__body--line2"><?=$m->odometer?> <?=$m->cost?> (<?=$m->quantity?>)</span>
                        </span>
                        <span class="app-list-item__controls">
                            <a href="<?=$this->url('application', ['controller'=>'vehicle','action'=>'editFueling'],['query'=>['vehicleId'=>$this->vehicle->id, 'id'=>$m->id]])?>"
                               class="icon-button">edit</a>
                            <a href="<?=$this->url('application', ['controller'=>'vehicle','action'=>'deleteFueling'],['query'=>['vehicleId'=>$this->vehicle->id, 'id'=>$m->id]])?>"
                               class="icon-button button-require-confirmation"
                               data-confirmation-message="Сигурни ли сте, че искате да изтриете този запис? (Операцията е необратима!)">delete</a>
                        </span>
                    </li>
                <?php } ?>
            </ul>
            <?php
            $firstPage = $this->pagination->firstPageToList();
            $lastPage = $this->pagination->lastPageToList();
            ?>
            <?php if ($lastPage > $firstPage) { ?>
                <div class="pagination">
                    <?php if ($firstPage > 1) { ?>
                        <a class="pagination-button material-symbols-sharp" href="<?=$this->url('application', ['controller'=>'vehicle', 'action'=>'fueling'], ['query'=>['vehicleId'=>$this->vehicle->id, 'page'=>1]])?>">first_page</a>
                    <?php } ?>
                    <?php for ($p = $firstPage; $p <= $lastPage && $p < $firstPage + 100; $p++) {?>
                        <a class="pagination-button" href="<?=$this->url('application', ['controller'=>'vehicle', 'action'=>'fueling'], ['query'=>['vehicleId'=>$this->vehicle->id, 'page'=>$p]])?>"><?=$p?></a>
                    <?php } ?>
                    <?php if ($lastPage < $this->pagination->getTotalPages()) { ?>
                        <a class="pagination-button material-symbols-sharp" href="<?=$this->url('application', ['controller'=>'vehicle', 'action'=>'fueling'], ['query'=>['vehicleId'=>$this->vehicle->id, 'page'=>$this->pagination->getTotalPages()]])?>">last_page</a>
                    <?php } ?>
                </div>
            <?php } ?>
        <?php } else { ?>
            <div class="content-stub">
                Няма въведени зареждания за <?=$this->vehicle->model?> <?=$this->vehicle->reg_nomer?>.
            </div>
        <?php } ?>
    </div>
</div>
<a class="fab" href="<?=$this->url('application', ['controller'=>'vehicle', 'action'=>'addFueling'], ['query'=>['vehicleId'=>$this->vehicle->id]])?>">add</a>
