<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
$this->headTitle('Видове поддръжка');
$this->headLink()->appendStylesheet($this->basePath('style/fuel.css'));
?><div class="page">
    <div class="list-panel">
        <?php if (!empty($this->models)) {?>
            <ul class="app-list fuel-list">
                <?php foreach ($this->models as $m) { ?>
                    <li class="app-list-item">
                        <span class="app-list-item__graphic"><span class="material-symbols-sharp">garage</span></span>
                        <span class="app-list-item__body">
                            <span class="app-list-item__body--line1"><?=$m->name?></span>
                        </span>
                        <span class="app-list-item__controls">
                            <a href="<?=$this->url('application', ['controller'=>'maintenance','action'=>'edit'],['query'=>['id'=>$m->id]])?>"
                               class="icon-button">edit</a>
                            <a href="<?=$this->url('application', ['controller'=>'maintenance','action'=>'delete'],['query'=>['id'=>$m->id]])?>"
                               class="icon-button button-require-confirmation"
                            data-confirmation-message="Сигурни ли сте, че искате да изтриете този вид поддръжка? (Операцията е необратима!)">delete</a>
                        </span>
                    </li>
                <?php } ?>
            </ul>
            <?php
                $firstPage = $this->pagination->firstPageToList();
                $lastPage = $this->pagination->lastPageToList();
            ?>
            <?php if ($lastPage > $firstPage) { ?>
                <div class="pagination">
                    <?php if ($firstPage > 1) { ?>
                        <a class="pagination-button material-symbols-sharp" href="<?=$this->url('application', ['controller'=>'fuel', 'action'=>'list'],['query'=>['page'=>1]])?>">first_page</a>
                    <?php } ?>
                    <?php for ($p = $firstPage; $p <= $lastPage && $p < $firstPage + 100; $p++) {?>
                        <a class="pagination-button" href="<?=$this->url('application', ['controller'=>'fuel', 'action'=>'list'],['query'=>['page'=>$p]])?>"><?=$p?></a>
                    <?php } ?>
                    <?php if ($lastPage < $this->pagination->getTotalPages()) { ?>
                        <a class="pagination-button material-symbols-sharp" href="<?=$this->url('application', ['controller'=>'fuel', 'action'=>'list'],['query'=>['page'=>$this->pagination->getTotalPages()]])?>">last_page</a>
                    <?php } ?>
                </div>
            <?php } ?>
        <?php } else { ?>
            <div class="content-stub">
                Няма въведени водове поддръжка!
            </div>
        <?php } ?>
    </div>
</div>
<a class="fab" href="<?=$this->url('application', ['controller'=>'maintenance', 'action'=>'add'])?>">add</a>
