<nav class="app-main-menu">
    <div class="menu-item">
        <a href="#"><span class="material-symbols-sharp menu-item__graphic">home</span>Начало</a>
    </div>
    <div class="menu-item">
        <a href="#"><span class="material-symbols-sharp menu-item__graphic">directions_car</span>Авто парк</a>
    </div>
    <div class="menu-item">
        <a href="#"><span class="material-symbols-sharp menu-item__graphic">group</span>Шофьори</a>
    </div>
    <div class="menu-item">
        <a href="#"><span class="material-symbols-sharp menu-item__graphic">location_city</span>Офиси</a>
    </div>
     <div class="menu-item">
        <a href="#"><span class="material-symbols-sharp menu-item__graphic">receipt_long</span>Пътен лист</a>
    </div>
    <div class="menu-item">
        <a href="#"><span class="material-symbols-sharp menu-item__graphic">build</span>Ремонт</a>
    </div>
    <div class="menu-item">
        <a href="#"><span class="material-symbols-sharp menu-item__graphic">local_gas_station</span>Зареждане на гориво</a>
    </div>
    <div class="menu-item">
        <a href="#"><span class="material-symbols-sharp menu-item__graphic">calendar_month</span>Годишна поддръжка</a>
    </div>
     <div class="menu-item">
        <a href="#"><span class="material-symbols-sharp menu-item__graphic">settings_suggest</span>Сервизно обслужване</a>
    </div>
    
</nav>



