<nav class="app-main-menu">
    <div class="menu-item">
        <a href="#"><span class="material-symbols-sharp menu-item__graphic">home</span>Начало</a>
    </div>
    <div class="menu-item">
        <a href="<?=$this->url('application', ['controller'=>'vehicle', 'action'=>'list'])?>"><span class="material-symbols-sharp menu-item__graphic">directions_car</span>Авто парк</a>
    </div>
     <div class="menu-item">
        <a href="#"><span class="material-symbols-sharp menu-item__graphic">receipt_long</span>Пътен лист</a>
    </div>
    <!--<div class="menu-item">
        <a href="#"><span class="material-symbols-sharp menu-item__graphic">build</span>Ремонт</a>
    </div>
    <div class="menu-item">
        <a href="#"><span class="material-symbols-sharp menu-item__graphic">local_gas_station</span>Зареждане на гориво</a>
    </div>
    <div class="menu-item">
        <a href="#"><span class="material-symbols-sharp menu-item__graphic">calendar_month</span>Годишна поддръжка</a>
    </div>-->
    <div class="menu-item">
        <a href="#"><span class="material-symbols-sharp menu-item__graphic">settings_suggest</span>Сервизно обслужване</a>
    </div>
    <div class="menu-item menu-item--has-submenu">
        <a href="#" class="menu-item__submenu-trigger"><span class="material-symbols-sharp menu-item__graphic">settings</span>Администриране</a>
        <div class="menu-item__submenu">
            <div class="menu-item">
                <a href="<?=$this->url('application', ['controller'=>'office', 'action'=>'list'])?>"><span class="material-symbols-sharp menu-item__graphic">location_city</span>Офиси</a>
            </div>
            <div class="menu-item">
                <a href="<?=$this->url('application', ['controller'=>'driver', 'action'=>'list'])?>"><span class="material-symbols-sharp menu-item__graphic">badge</span>Шофьори</a>
            </div>
            <div class="menu-item">
                <a href="<?=$this->url('application', ['controller'=>'fuel', 'action'=>'list'])?>"><span class="material-symbols-sharp menu-item__graphic">local_gas_station</span>Видове гориво</a>
            </div>
            <div class="menu-item">
                <a href="<?=$this->url('application', ['controller'=>'maintenance', 'action'=>'list'])?>"><span class="material-symbols-sharp menu-item__graphic">garage</span>Видове поддръжка</a>
            </div>
            <div class="menu-item">
                <a href="<?=$this->url('application', ['controller'=>'user', 'action'=>'list'])?>"><span class="material-symbols-sharp menu-item__graphic">group</span>Потребители</a>
            </div>
        </div>
    </div>
    
</nav>



