<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <?=$this->partial('layout/_head-html.phtml')?>
    <body>
    <?php if ($this->identity()) {?>
    <?=$this->partial('layout/_app-drawer.phtml')?>
    <?php } ?>
        <div class="app-main">
            <?php if ($this->identity()) {?>
            <header class="app-bar">
                <button
                        class="app-drawer-toggle app-bar__left-button"
                        type="button"
                        data-target="#appDrawer"
                        aria-controls="appDrawer"
                        aria-expanded="false"
                        aria-label="Отваряне на менюто"
                >
                    <span class="material-symbols-sharp">menu</span>
                </button>
                <span class="app-bar__title">

                </span>
            </header>
            <?php } ?>
            <main class="app-content<?= $this->identity() ? ' app-bar-page--fix' : ''?>" id="mainContent">
                <?= $this->content ?>
            </main>
        </div>


        <?= $this->inlineScript()
            /*->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) */?>
    </body>
</html>
