<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
$this->headTitle('Потребители');
$this->headLink()->appendStylesheet($this->basePath('style/user.css'));
?><div class="page">
    <div class="list-panel">
        <?php if (!empty($this->users)) {?>
            <ul class="app-list users-list">
                <?php foreach ($this->users as $u) {
                    $driver = $u->getDriver();
                    ?>
                    <li class="app-list-item">
                        <span class="app-list-item__graphic"><span class="material-symbols-sharp">person</span></span>
                        <span class="app-list-item__body">
                            <span class="app-list-item__body--line1"><?=$u->name?></span>
                            <span class="app-list-item__body--line2">
                                <span class="list-details"><span class="material-symbols-sharp">alternate_email</span><?=$u->username?></span>
                                <?php if(!empty($driver)){?>
                                <span class="list-details"><span class="material-symbols-sharp">badge</span> <a href="<?=$this->url('application', ['controller'=>'driver','action'=>'edit'],['query'=>['id'=>$driver->id]])?>"><?=$driver->name?></a></span>
                                <?php }?>
                            </span>
                        </span>
                        <span class="app-list-item__controls">
                            <a href="<?=$this->url('application', ['controller'=>'user','action'=>'edit'],['query'=>['id'=>$u->id]])?>"
                               class="icon-button">edit</a>
                            <a href="<?=$this->url('application', ['controller'=>'user','action'=>'setCustomPass'],['query'=>['id'=>$u->id]])?>"
                               class="icon-button">password</a>
                            <a href="<?=$this->url('application', ['controller'=>'user','action'=>'delete'],['query'=>['id'=>$u->id]])?>"
                               class="icon-button button-require-confirmation"
                            data-confirmation-message="Сигурни ли сте, че искате да изтриете този потребител? (Операцията е необратима!)">delete</a>
                        </span>
                    </li>
                <?php } ?>
            </ul>
            <?php
                $firstPage = $this->pagination->firstPageToList();
                $lastPage = $this->pagination->lastPageToList();
            ?>
            <?php if ($lastPage > $firstPage) { ?>
                <div class="pagination">
                    <?php if ($firstPage > 1) { ?>
                        <a class="pagination-button material-symbols-sharp" href="<?=$this->url('application', ['controller'=>'user', 'action'=>'list'],['query'=>['page'=>1]])?>">first_page</a>
                    <?php } ?>
                    <?php for ($p = $firstPage; $p <= $lastPage && $p < $firstPage + 100; $p++) {?>
                        <a class="pagination-button" href="<?=$this->url('application', ['controller'=>'user', 'action'=>'list'],['query'=>['page'=>$p]])?>"><?=$p?></a>
                    <?php } ?>
                    <?php if ($lastPage < $this->pagination->getTotalPages()) { ?>
                        <a class="pagination-button material-symbols-sharp" href="<?=$this->url('application', ['controller'=>'user', 'action'=>'list'],['query'=>['page'=>$this->pagination->getTotalPages()]])?>">last_page</a>

                    <?php } ?>
                </div>
            <?php } ?>
        <?php } ?>
    </div>
</div>
<a class="fab" href="<?=$this->url('application', ['controller'=>'user', 'action'=>'add'])?>">add</a>
