<?php
/** @var \Laminas\View\Renderer\PhpRenderer $this */
$this->headTitle($this->title);
$this->headLink()->appendStylesheet($this->basePath('style/user.css'));
?><section class="page">
    <div class="form-panel">
        <div class="form-field-wrapper"><label for="inp-name">Име</label>
            <input type="text" name="name" id="inp-name" value="<?=$this->model->name??''?>" readonly></div>
        <?php if(!$this->dontShowForm??false) { ?>
            <form action="" method="post">
                <input type="hidden" name="id" value="<?=$this->model->id??''?>">
                <div class="form-fields">
                    <div class="form-field-wrapper"><label for="inp-password">Нова парола</label>
                        <input type="password" name="password" id="inp-password" value="<?=$this->password??''?>"></label></div>
                    <div class="form-field-wrapper"><label for="inp-password2">Потвърди парола</label>
                        <input type="password" name="password2" id="inp-password2" value="<?=$this->password2??''?>"></label></div>
                </div>
                <div class="form-controls">
                    <a class="button" href="<?=$this->backlink?>"><span class="material-symbols-sharp">arrow_back</span> Назад</a>
                    <button><span class="material-symbols-sharp">save</span> Запис</button>
                </div>
            </form>
        <?php } else { ?>
            <div class="form-controls">
                <a class="button" href="<?=$this->backlink?>"><span class="material-symbols-sharp">arrow_back</span> Назад</a>
                <button><span class="material-symbols-sharp">save</span> Запис</button>
            </div>
        <?php }?>
    </div>
</section>
